# -*- coding: utf-8 -*-
"""LCS

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HxHOy_b3-4G9ELg4dp_JJQy0p3Wcd3Sj
"""

def lcs_algo(S1, S2, m, n):
    L = [[0 for x in range(n+1)] for x in range(m+1)]

    # Building the mtrix in bottom-up way
    for i in range(m+1):
        for j in range(n+1):
            if i == 0 or j == 0:
                L[i][j] = 0
            elif S1[i-1] == S2[j-1]:
                L[i][j] = L[i-1][j-1] + 1
            else:
                L[i][j] = max(L[i-1][j], L[i][j-1])

    index = L[m][n]

    lcs_algo = [""] * (index+1)
    lcs_algo[index] = ""

    i = m
    j = n
    while i > 0 and j > 0:

        if S1[i-1] == S2[j-1]:
            lcs_algo[index-1] = S1[i-1]
            i -= 1
            j -= 1
            index -= 1

        elif L[i-1][j] > L[i][j-1]:
            i -= 1
        else:
            j -= 1
            
    # Printing the sub sequences
    return "".join(lcs_algo)
    # return result

with open('/gdrive/My Drive/IR Research/Corpus/Spanish/spanishCorpusSmallest.txt', 'r' , encoding = "ISO-8859-1") as f1:
    S1 = f1.read()
with open('/gdrive/My Drive/IR Research/Corpus/Spanish/spanishCorpusSmallest.txt', 'r' , encoding = "ISO-8859-1") as f2:
    S2 = f2.read()
m = len(S1)
n = len(S2)
lcs_algo(S1, S2, m, n)

S1 = "ACADB"
S2 = "CBDA"
m = len(S1)
n = len(S2)
print(lcs_algo(S1, S2, m, n))

